PythonConnect/PythonConnect/urls.py
from django.contrib import admin
from django.urls import path, include # includeを追記

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path(r'', include('sample.urls')), # ここを追記
    path('app/', include('tag.urls')),
    path('cognitoSample/', include('cognitoSample.urls')),#cognitoSample
]

PythonConnect/sample/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    # path(r'', views.index, name='index'),
    path('seo/', views.YoutubeSEO, name='YoutubeSEO'),
    # 以下を追記(views.pyのcall_write_data()にデータを送信できるようにする)
    path("ajax/", views.call_write_data, name="call_write_data"),
    path("app/seo/", views.no_url, name="no_url_YoutubeSEO"),
    path("app/seo_out/", views.no_url, name="no_url_YoutubeSEO_out"),
    path("app/Terms_service/", views.Terms_service, name="Terms_service"),
]

PythonConnect/tag/urls.py
from django.urls import path
from . import views
# from django.conf import settings
# from django.contrib.staticfiles import views
# from django.urls import re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'app'
urlpatterns = [
    path(r'', views.SearchTAG, name='SearchTAG'),
    path("tag/ajax/", views.call_write_word, name="call_write_word"),
    path("index/", views.index, name="index"),
    path("tag/", views.no_url, name="no_url_SearchTAG"),
    path("tag_out/", views.no_url, name="no_url_SearchTAG_out"),
]
urlpatterns += staticfiles_urlpatterns()
# #for static method
# if settings.DEBUG:
#     urlpatterns += [
#         re_path(r'^static/(?P<path>.*)$', views.serve),
#     ]

PythonConnect/templates/SearchTAG(タグのみ＋コピー用文字列出力).html
<!-- {% load static %} -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HTML</title>
    <!-- <link rel='stylesheet' type='text/css' href="{% static 'style.css' %}"/>
    <script type="text/javascript" src="{% static 'script.js' %}"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Bootstrap Javascript(jQuery含む) -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">タグ検索サイト</h1>
          <form>
            <label class="col-5">最適化したい単語を入力してください。</label>
            <div class="input-group col-5">
              <input type="text" class="form-control" id="input_word"/>
              <span class="input-group-btn">
                <button type="button" onclick="clickBtn()" class="btn btn-primary">検索</button>
              </span>
            </div>
          </form>
        </div>
      </div>

      <div class="table-responsive col-5">
        <table class="table table-sm table-bordered">
          <tbody>
            <tr>
              <th>no</th>
              <th>tags</th>
              <th>tagNm</th>
            </tr>
          </tbody>
          <tbody id='tagTbody'>
          </tbody>
        </table>
      </div>
      <h2>tags</h2>
      <!-- URLコピー用 -->
      <p id='tags'></p>

      <script>
        function clickBtn() {
          $("#titleTbody").empty();
          $("#tagTbody").empty();
          $("#url").text("");
          $('#tags').text("");
          var word = document.getElementById("input_word").value;
          var data =
            {
              "word":word,
            };
          $.ajax({
            //AWSのサーバーIP,URLに変える
            // url: "{% url 'tag:call_write_word' %}",
            // url: "/tag/ajax/",
            url: "https://kotatsu.tv:8000/tag/ajax/",
            method: 'GET',
            data: {"input_word": JSON.stringify(data)},
            dataType: "json",
            contentType: "application/json",
            beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
              }
            },
            error: function(xhr, status, error) {
              console.log("error")
            }
          })
          .done(function(data) {
            console.log("Success"); 
          })
          .done(function(response){
            format(response);
            $('#tags').text(response.tags);
          });

          // csrf_tokenの取得に使う
          function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
                }
              }
            }
            return cookieValue;
          }

          // ヘッダにcsrf_tokenを付与する関数
          function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
          };
        }

        // 取得結果を整形する
        // @param response
        function format(response) {
            // タイトル&概要
            response.title.forEach(function(element, index){
              console.log('Index:' + index);
              console.log('Element:' + element);
              response.description.forEach(function(element2, index2){
                console.log('Index:' + index2);
                console.log('Element:' + element2);
                if(index == index2){
                  var no = 1;
                  no += index;
                  $('#titleTbody').append('<tr><td>' + no + '</td><td>'+ element +'</td><<td><font size="1">' 
                    + element2.replace(/(\r\n|\n|\r)/gm, '<br>') + '</font></td></tr>');
                }
              });
            });
            // url
            $('#url').text('url:' + response.url);
            // タグ
            response.tags.forEach(function(element, index){
              console.log('Index:' + index);
              console.log('Element:' + element);
              response.tagNum.forEach(function(element2, index2){
                console.log('Index:' + index2);
                console.log('Element:' + element2);
                if(index == index2){
                  var no = 1;
                  no += index;
                  $('#tagTbody').append('<tr><td>' + no + '</td><td>' + element +'</td><<td>' + element2 + '</td></tr>');
                }
              });
            });
          }
      </script>
  </body>
</html>

PythonConnect/templates/SearchTAG.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HTML</title>
    <!-- <link rel='stylesheet' type='text/css' href="{% static 'style.css' %}"/>
    <script type="text/javascript" src="{% static 'script.js' %}"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Bootstrap Javascript(jQuery含む) -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">タグ検索サイト</h1>
          <form>
            <label class="col-5">最適化したい単語を入力してください。</label>
            <div class="input-group col-5">
              <input type="text" class="form-control" id="input_word"/>
              <span class="input-group-btn">
                <button type="button" onclick="clickBtn()" class="btn btn-primary">検索</button>
              </span>
            </div>
          </form>
        </div>
      </div>

      <div class="table-responsive col-5">
        <table class="table table-sm table-bordered">
          <tbody>
            <tr>
              <th>no</th>
              <th>tags</th>
              <th>tagNm</th>
            </tr>
          </tbody>
          <tbody id='tagTbody'>
          </tbody>
        </table>
      </div>
      <h2>tags</h2>
      <!-- URLコピー用 -->
      <p id='tags'></p>

      <script>
        function clickBtn() {
          $("#titleTbody").empty();
          $("#tagTbody").empty();
          $("#url").text("");
          $('#tags').text("");
          var word = document.getElementById("input_word").value;
          var data =
            {
              "word":word,
            };
          $.ajax({
            //AWSのサーバーIP,URLに変える
            url: "{% url 'tag:call_write_word' %}",
            // url: "/tag/ajax/",
            // url: "https://kotatsu.tv:8000/tag/ajax/",
            method: 'GET',
            data: {"input_word": JSON.stringify(data)},
            dataType: "json",
            contentType: "application/json",
            beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
              }
            },
            error: function(xhr, status, error) {
              console.log("error")
            }
          })
          .done(function(data) {
            console.log("Success"); 
          })
          .done(function(response){
            format(response);
            $('#tags').text(response.tags);
          });

          // csrf_tokenの取得に使う
          function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
                }
              }
            }
            return cookieValue;
          }

          // ヘッダにcsrf_tokenを付与する関数
          function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
          };
        }

        // 取得結果を整形する
        // @param response
        function format(response) {
            // タイトル&概要
            response.title.forEach(function(element, index){
              console.log('Index:' + index);
              console.log('Element:' + element);
              response.description.forEach(function(element2, index2){
                console.log('Index:' + index2);
                console.log('Element:' + element2);
                if(index == index2){
                  var no = 1;
                  no += index;
                  $('#titleTbody').append('<tr><td>' + no + '</td><td>'+ element +'</td><<td><font size="1">' 
                    + element2.replace(/(\r\n|\n|\r)/gm, '<br>') + '</font></td></tr>');
                }
              });
            });
            // url
            $('#url').text('url:' + response.url);
            // タグ
            response.tags.forEach(function(element, index){
              console.log('Index:' + index);
              console.log('Element:' + element);
              response.tagNum.forEach(function(element2, index2){
                console.log('Index:' + index2);
                console.log('Element:' + element2);
                if(index == index2){
                  var no = 1;
                  no += index;
                  $('#tagTbody').append('<tr><td>' + no + '</td><td>' + element +'</td><<td>' + element2 + '</td></tr>');
                }
              });
            });
          }
      </script>
  </body>
</html>

PythonConnect/templates/SearchTAG_ori.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HTML</title>
    <!-- <link rel='stylesheet' type='text/css' href="{% static 'style.css' %}"/>
    <script type="text/javascript" src="{% static 'script.js' %}"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>
      <h1>タグ検索サイト</h1>
      <span>最適化したい単語を入力してください。</span>
      <input type="text" size="50" id="input_word">
      <button type="button" onclick="clickBtn()">セット</button>

      <h2>title</h2>
      <p id='title'></p>
      <h2>url</h2>
      <p id='url'></p>
      <h2>description</h2>
      <p id='description'></p>
      <h2>tags</h2>
      <p id='tags'></p>
      <p id='tagNum'></p>

      <div class="result">
      </div>

      <script>
        function clickBtn() {
            $('#title').text("");
            $('#url').text("");
            $('#description').text("");
            $('#tags').text("");
          var word = document.getElementById("input_word").value;
          var data =
            {
              "word":word,
            };

          $.ajax({
            //AWSのサーバーIP,URLに変える
            // url: "{% url 'tag:call_write_word' %}",
            // url: "/tag/ajax/",
            url: "http://52.199.115.16:8000/tag/ajax/",
            method: 'GET',
            data: {"input_word": JSON.stringify(data)},
            dataType: "json",
            contentType: "application/json",
            beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
              }
            },
            error: function(xhr, status, error) {
              console.log("error")
            }
          })
          .done(function(data) {
            console.log("Success"); 
          })
          .done(function(response){
            // $('.result').prepend('<p>title' + response.title + '</p>');
            $('#title').text(response.title);
            // $('.result').prepend('<p>url' + response.url + '</p>');
            $('#url').text(response.url);
            // $('.result').prepend('<p>tags' + response.tags + '</p>');
            $('#description').text(response.description);
            // $('.result').prepend('<p>description' + response.description + '</p>');
            $('#tags').text(response.tags);
            $('#tagNum').text(response.tagNum);
          });

          // csrf_tokenの取得に使う
          function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
                }
              }
            }
            return cookieValue;
          }

          // ヘッダにcsrf_tokenを付与する関数
          function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
          };

          

        }

      </script>
  </body>
</html>

PythonConnect/templates/SearchTAGのコピー.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HTML</title>
    <!-- <link rel='stylesheet' type='text/css' href="{% static 'style.css' %}"/>
    <script type="text/javascript" src="{% static 'script.js' %}"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Bootstrap Javascript(jQuery含む) -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">タグ検索サイト</h1>
          <form>
            <label class="col-5">最適化したい単語を入力してください。</label>
            <div class="input-group col-5">
              <input type="text" class="form-control" id="input_word"/>
              <span class="input-group-btn">
                <button type="button" onclick="clickBtn()" class="btn btn-primary">検索</button>
              </span>
            </div>
          </form>
        </div>
      </div>
<!-- 
      <div class="table-responsive col-12">
        <table class="table table-sm table-bordered"> 
          <tbody>
            <tr>
              <th>no</th>
              <th>title</th>
              <th>description</th>
            </tr>
          </tbody>
          <tbody id='titleTbody'>
          </tbody>
        </table>
      </div> -->

      <div class="table-responsive col-5">
        <table class="table table-sm table-bordered">
          <tbody>
            <tr>
              <th>no</th>
              <th>tags</th>
              <th>tagNm</th>
            </tr>
          </tbody>
          <tbody id='tagTbody'>
          </tbody>
        </table>
      </div>
      <!-- <p id='url'></p> -->

      <script>
        function clickBtn() {
          $("#titleTbody").empty();
          $("#tagTbody").empty();
          $("#url").text("");
          var word = document.getElementById("input_word").value;
          var data =
            {
              "word":word,
            };
          $.ajax({
            //AWSのサーバーIP,URLに変える
            // url: "{% url 'tag:call_write_word' %}",
            // url: "/tag/ajax/",
            url: "https://kotatsu.tv:8000/tag/ajax/",
            method: 'GET',
            data: {"input_word": JSON.stringify(data)},
            dataType: "json",
            contentType: "application/json",
            beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
              }
            },
            error: function(xhr, status, error) {
              console.log("error")
            }
          })
          .done(function(data) {
            console.log("Success"); 
          })
          .done(function(response){
            format(response);
          });

          // csrf_tokenの取得に使う
          function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
                }
              }
            }
            return cookieValue;
          }

          // ヘッダにcsrf_tokenを付与する関数
          function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
          };
        }

        // 取得結果を整形する
        // @param response
        function format(response) {
            // タイトル&概要
            response.title.forEach(function(element, index){
              console.log('Index:' + index);
              console.log('Element:' + element);
              response.description.forEach(function(element2, index2){
                console.log('Index:' + index2);
                console.log('Element:' + element2);
                if(index == index2){
                  var no = 1;
                  no += index;
                  $('#titleTbody').append('<tr><td>' + no + '</td><td>'+ element +'</td><<td><font size="1">' 
                    + element2.replace(/(\r\n|\n|\r)/gm, '<br>') + '</font></td></tr>');
                }
              });
            });
            // url
            $('#url').text('url:' + response.url);
            // タグ
            response.tags.forEach(function(element, index){
              console.log('Index:' + index);
              console.log('Element:' + element);
              response.tagNum.forEach(function(element2, index2){
                console.log('Index:' + index2);
                console.log('Element:' + element2);
                if(index == index2){
                  var no = 1;
                  no += index;
                  $('#tagTbody').append('<tr><td>' + no + '</td><td>' + element +'</td><<td>' + element2 + '</td></tr>');
                }
              });
            });
          }
      </script>
  </body>
</html>

PythonConnect/templates/YoutubeSEO.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HTML</title>
    <!-- <link rel='stylesheet' type='text/css' href="{% static 'style.css' %}"/>
    <script type="text/javascript" src="{% static 'script.js' %}"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>
    <h1>Youtube解析サイト</h1>
      <span>あなたのYoutube動画URLをコピペしてください。</span>
      <br>
      <input type="text" size="50" id="input_form">
      <br>
      <span>以下に最適化したいワードを登録してください。</span>
      <br>
      <input type="text" size="50" id="input_word">
      <button type="button" onclick="clickBtn()">セット</button>

      <h2>state</h2>
      <p id='string'></p>
      <h2>title</h2>
      <p id='titleRate'></p>
      <p id='title'></p>
      <h2>description</h2>
      <p id='descriptionRate'></p>
      <p id='description'></p>
      <h2>tags</h2>
      <p id='tagRate'></p>
      <p id='tags'></p>
      <h2>url</h2>
      <p id='urlScore'></p>
      <p id='url'></p>
      <h2>TotalScore</h2>
      <p id='TotalScore'></p>
      <script>
        function clickBtn() {

          $('#title').text("");
          $('#titleRate').text("");
          $('#description').text("");
          $('#descriptionRate').text("");
          $('#tags').text("");
          $('#tagRate').text("");
          $('#urlScore').text("");
          $('#url').text("");
          $('#TotalScore').text("");
          $('#string').text("");
          var url = document.getElementById("input_form").value;
          var word = document.getElementById("input_word").value;
          var data =
            {
              "url":url,
              "word":word,
            };

          $.ajax({
            // url: "https://kotatsu.tv:8000/ajax/",
            url: "{% url 'myapp:call_write_data' %}",
            method: 'GET',
            data: {"input_data": JSON.stringify(data)},
            dataType: "json",
            contentType: "application/json",
            beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
              }
            },
            error: function(xhr, status, error) {
              console.log("error")
            }
          })
          .done(function(data) {
            console.log("Success"); 
          })
          .done(function(response){

            console.log("response");
            $('#title').text(response.title);
            $('#titleRate').text(response.titleRate);
            $('#description').text(response.description);
            $('#descriptionRate').text(response.descriptionRate);
            $('#tags').text(response.tags);
            $('#tagRate').text(response.tagRate);
            $('#urlScore').text(response.urlScore);
            $('#url').text(response.url);
            $('#TotalScore').text(response.TotalScore);
            $('#string').text(response.string);
          });

          // csrf_tokenの取得に使う
          function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
                }
              }
            }
            return cookieValue;
          }

          // ヘッダにcsrf_tokenを付与する関数
          function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
          };
        }

      </script>
  </body>
</html>

PythonConnect/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HTML</title>
    <link rel='stylesheet' type='text/css' href="{% static 'style.css' %}"/>
    <script type="text/javascript" src="{% static 'script.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>
    
    <h1>Youtube分析サイト</h1>
    <a href= "app/seo/" >SEO対策チェッカー</a>
    <a href= "app/tag/" >TAG自動検索</a>
     
  </body>
</html>